//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Тортуга_3исп11_17_Маханов.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryFood
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CategoryFood()
        {
            this.FoodItem = new HashSet<FoodItem>();
        }
    
        public int IdCategory { get; set; }
        public string Name { get; set; }
        public string ImagePath { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FoodItem> FoodItem { get; set; }
        public virtual string LocalImagePath { get { return "/Тортуга 3исп11-17 Маханов;component/" + ImagePath.Substring(8); } }
    }
}
